/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractExternalizedBean.as).
 */

package org.xreport.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class AbstractExternalizedBeanBase implements IExternalizable {

        private var _persistState:int;

        public function set persistState(value:int):void {
            _persistState = value;
        }
        public function get persistState():int {
            return _persistState;
        }

        public function readExternal(input:IDataInput):void {
            _persistState = input.readObject() as int;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject((_persistState is IPropertyHolder) ? IPropertyHolder(_persistState).object : _persistState);
        }
    }
}