/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.xreport.entities {
    [Bindable]
    [RemoteClass(alias="org.xreport.entities.Parameter")]
    public class Parameter extends ParameterBase {
		public static const PARAM_PERIOD:String='period';
		public static const PARAM_PERIODT:String='periodt';
		public static const PARAM_DATE:String='pdate';
		public static const PARAM_STORE:String='pstore';
		public static const PARAM_CAFE:String='pcafe';
    }
}