/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.xreport.entities {

    [Bindable]
    [RemoteClass(alias="org.xreport.entities.ReportSchedule")]
    public class ReportSchedule extends ReportScheduleBase {

        public function ReportSchedule() {
            super();
        }
    }
}