/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ReportParameter.as).
 */

package org.xreport.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class ReportParameterBase extends AbstractExternalizedBean {

        private var _parameter:String;
        private var _report:String;

        public function set parameter(value:String):void {
            _parameter = value;
        }
        public function get parameter():String {
            return _parameter;
        }

        public function set report(value:String):void {
            _report = value;
        }
        public function get report():String {
            return _report;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _parameter = input.readObject() as String;
            _report = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_parameter is IPropertyHolder) ? IPropertyHolder(_parameter).object : _parameter);
            output.writeObject((_report is IPropertyHolder) ? IPropertyHolder(_report).object : _report);
        }
    }
}