/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ReportResult.as).
 */

package org.xreport.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class ReportResultBase extends AbstractExternalizedBean {

        public function ReportResultBase() {
            super();
        }

        private var _error:String;
        private var _hasError:Boolean;
        private var _id:String;
        private var _url:String;

        public function set error(value:String):void {
            _error = value;
        }
        public function get error():String {
            return _error;
        }

        public function set hasError(value:Boolean):void {
            _hasError = value;
        }
        public function get hasError():Boolean {
            return _hasError;
        }

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set url(value:String):void {
            _url = value;
        }
        public function get url():String {
            return _url;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _error = input.readObject() as String;
            _hasError = input.readObject() as Boolean;
            _id = input.readObject() as String;
            _url = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_error is IPropertyHolder) ? IPropertyHolder(_error).object : _error);
            output.writeObject((_hasError is IPropertyHolder) ? IPropertyHolder(_hasError).object : _hasError);
            output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id);
            output.writeObject((_url is IPropertyHolder) ? IPropertyHolder(_url).object : _url);
        }
    }
}