/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.xreport.entities {

    [Bindable]
    [RemoteClass(alias="org.xreport.entities.Source")]
    public class Source extends SourceBase {
    }
}